# user specifiable configurations go here

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          client-id: TiCatApp
          role:
            admin: TiCatApp_admin
            user: TiCatApp_user
          issuer-uri:  http://localhost:8080/realms/TiCat
          jwk-set-uri: http://localhost:8080/realms/TiCat/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:5432/ticatapp
    username: ticatapp
    password: ticatappsupersecret